name: quantum
description: A flutter plugin for dream project.
version: 0.0.1 

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.11.0"

flutter:
  assets:
    - resources/jieba/dicts/
    - resources/jieba/dicts/pos_dict/
  plugin:
    platforms:
      android:
        package: direct.multiverse.quantum
        pluginClass: QuantumPlugin
      ios:
        pluginClass: QuantumPlugin
      macos:
        pluginClass: QuantumPlugin
      windows:
        pluginClass: QuantumPlugin
      linux:
        pluginClass: QuantumPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  ffigen: ^7.2.4
  sqlite3_flutter_libs: ^0.5.12
  sqlite3: ^1.9.1
  js: ^0.6.1
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
